
services:
  app:
    env_file:
      - ".env"
    restart: always
    build: .
    ports:
      - "8080:8080"
    networks:
      - ev-network

  postgres:
    env_file:
      - ".env"
    image: postgres:17
#    container_name: evcharging-database
    ports:
      - "5432:5432"
    restart: always
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    networks:
      - ev-network
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
      - ev-data:/var/lib/postgresql/data

networks:
  ev-network:
    driver: bridge

volumes:
  ev-data: