services:
#  mqtt-broker:
#    image: eclipse-mosquitto
#    container_name: mqtt-broker
#    ports:
#      - "1883:1883"
#      - "9001:9001"
#    volumes:
#      - ./mosquitto/config:/mosquitto/config
#    networks:
#      - ev-network

  app:
    env_file:
      - ".env"
    restart: always
    build: .
    # ports:
    #   - "8080"
    networks:
      - ev-network
      - traefik-proxy
    depends_on:
      postgres:
        condition: service_healthy
#      mqtt-broker:
#        condition: service_started
#This comment is for reuse
    labels:
      - "traefik.enable=true"
      - "traefik.docker.network=traefik-proxy"
      - "traefik.http.routers.${COMPOSE_PROJECT_NAME}.rule=Host(`${COMPOSE_PROJECT_NAME}.${TRAEFIK_HOST}`)"
      - "traefik.http.routers.${COMPOSE_PROJECT_NAME}.entrypoints=websecure"
      - "traefik.http.routers.${COMPOSE_PROJECT_NAME}.tls.certresolver=letsencrypt"
      - "traefik.http.services.${COMPOSE_PROJECT_NAME}.loadbalancer.server.port=8080"

  postgres:
    env_file:
      - ".env"
    image: pgrouting/pgrouting:16-3.5-4.0
    #    container_name: evcharging-database
    ports:
      - "5432"
    restart: always
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    networks:
      - ev-network
    volumes:
      - ./sql_script/init.sql:/docker-entrypoint-initdb.d/init.sql
      - ev-data:/var/lib/postgresql/data
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U ${DB_USERNAME} -d ${DB_NAME}" ]
      interval: 5s
      timeout: 5s
      retries: 5

#  osm-importer:
#    image: iboates/osm2pgrouting
#    entrypoint: ["/bin/sh", "-c"]
#    command: >
#      "
#      export PGPASSWORD=${DB_PASSWORD};
#
#      echo 'Đang import dữ liệu bản đồ...';
#      osm2pgrouting -f /map_data/hcmc.osm -h postgres -p ${DB_PORT} -U ${DB_USERNAME} -d ${DB_NAME} -W ${DB_PASSWORD} --conf /usr/share/osm2pgrouting/mapconfig.xml --clean;
#      "
#    volumes:
#      - ./map_data:/map_data
#    networks:
#      - ev-network
#    depends_on:
#      postgres:
#        condition: service_healthy
#    restart: "no"
#    profiles:
#      - setup

  osm_importer:
    image: postgres:16-alpine
    env_file:
      - ".env"
    volumes:
      - ./map_data:/map_data
    networks:
      - ev-network
    depends_on:
      postgres:
        condition: service_healthy
    command: >
      sh -c '
            export PGPASSWORD=$$DB_PASSWORD
            echo "Importing map data"
            psql -h postgres -U $$DB_USERNAME -d $$DB_NAME -f /map_data/hcmc_2po_4pgr.sql
      '
    restart: no
    profiles:
      - setup

  data-seeder:
    image: postgres:16-alpine
    env_file:
      - ".env"
    volumes:
      - ./simulated_data:/simulated_data
    networks:
      - ev-network
    depends_on:
      postgres:
        condition: service_healthy
      app:
        condition: service_started
    command: >
      sh -c '
            echo "Đang chờ Spring Boot (JPA) tạo schema (20s)..."
            sleep 20

            export PGPASSWORD=$$DB_PASSWORD

            echo "Kiểm tra dữ liệu hiện tại..."
            DATA_EXISTS=$$(psql -h postgres -U $$DB_USERNAME -d $$DB_NAME -tAc "SELECT EXISTS (SELECT 1 FROM charging_station LIMIT 1);")

            if [ "$$DATA_EXISTS" = "t" ]; then
              echo "Dữ liệu trạm sạc đã tồn tại. Bỏ qua seeding."
            else
              echo "Bắt đầu import simulated data..."
              psql -h postgres -U $$DB_USERNAME -d $$DB_NAME -f /simulated_data/insert_data.sql
              echo "Import hoàn tất!"
            fi
      '
    restart: "no"
    profiles:
      - setup

networks:
  ev-network:
    driver: bridge
  traefik-proxy:
    external: true

volumes:
  ev-data:
