import { ChargingStation } from "@/models/station";

export const sampleStations: ChargingStation[] = [
    {
        id: 1,
        name: "Station 1",
        operatorId: 1,
        addressInfor: "District 1, Ho Chi Minh City",
        totalPoints: 2,
        status: "active",
        latitude: 10.7769,
        longtitude: 106.7009,
        chargingPoints: [
            {
                id: 101,
                stationId: 1,
                status: "available",
                Connectors: [
                    {
                        id: 1001,
                        pointId: 101,
                        type: "Type 2",
                        maxPowerKW: 22,
                        voltageV: 400,
                    },
                    {
                        id: 1002,
                        pointId: 101,
                        type: "CCS",
                        maxPowerKW: 50,
                        voltageV: 800,
                    },
                ],
            },
            {
                id: 102,
                stationId: 1,
                status: "busy",
                Connectors: [
                    {
                        id: 1003,
                        pointId: 102,
                        type: "Type 1",
                        maxPowerKW: 7.4,
                        voltageV: 230,
                    },
                ],
            },
        ],
    },

    {
        id: 2,
        name: "Station 2",
        operatorId: 1,
        addressInfor: "District 2, Ho Chi Minh City",
        totalPoints: 1,
        status: "maintenance",
        latitude: 10.7798,
        longtitude: 106.7153,
        chargingPoints: [
            {
                id: 201,
                stationId: 2,
                status: "offline",
                Connectors: [
                    {
                        id: 2001,
                        pointId: 201,
                        type: "CHAdeMO",
                        maxPowerKW: 50,
                        voltageV: 500,
                    },
                ],
            },
        ],
    },

    {
        id: 3,
        name: "Green Boost Hai Bà Trưng",
        operatorId: 3,
        addressInfor: "123 Hai Bà Trưng, Phường 6, Hồ Chí Minh",
        totalPoints: 5,
        status: "Đang hoạt động",
        latitude: 10.7842,
        longtitude: 106.6968,
        img: ["https://th.bing.com/th/id/R.1c6f8aee48e94773128c686db96a5320?rik=xxLQoQs3YtfAVg&pid=ImgRaw&r=0"],
        chargingPoints: [
            {
                id: 301,
                stationId: 3,
                status: "available",
                Connectors: [
                    {
                        id: 3001,
                        pointId: 301,
                        type: "Type 2",
                        maxPowerKW: 11,
                        voltageV: 400,
                    },
                ],
            },
            {
                id: 302,
                stationId: 3,
                status: "busy",
                Connectors: [
                    {
                        id: 3002,
                        pointId: 302,
                        type: "CCS",
                        maxPowerKW: 100,
                        voltageV: 800,
                    }, {
                        id: 30021,
                        pointId: 302,
                        type: "Type 2",
                        maxPowerKW: 100,
                        voltageV: 800,
                    },
                ],
            },
            {
                id: 303,
                stationId: 3,
                status: "available",
                Connectors: [
                    {
                        id: 3002,
                        pointId: 302,
                        type: "CCS",
                        maxPowerKW: 100,
                        voltageV: 800,
                    },
                ],
            },
            {
                id: 304,
                stationId: 3,
                status: "busy",
                Connectors: [
                    {
                        id: 3002,
                        pointId: 302,
                        type: "CCS",
                        maxPowerKW: 100,
                        voltageV: 800,
                    },
                ],
            },
            {
                id: 305,
                stationId: 3,
                status: "busy",
                Connectors: [
                    {
                        id: 3002,
                        pointId: 302,
                        type: "CCS",
                        maxPowerKW: 100,
                        voltageV: 800,
                    },
                ],
            },
        ],
    },
    {
        id: 4,
        name: "Station 4",
        operatorId: 2,
        addressInfor: "District 4, Ho Chi Minh City",
        totalPoints: 3,
        chargingPoints: [],
        status: "active",
        latitude: 10.7644,
        longtitude: 106.7042,
    },
    {
        id: 5,
        name: "Station 5",
        operatorId: 2,
        addressInfor: "District 5, Ho Chi Minh City",
        totalPoints: 7,
        chargingPoints: [],
        status: "busy",
        latitude: 10.7596,
        longtitude: 106.6828,
    },
    {
        id: 6,
        name: "Station 6",
        operatorId: 3,
        addressInfor: "District 6, Ho Chi Minh City",
        totalPoints: 4,
        chargingPoints: [],
        status: "offline",
        latitude: 10.7522,
        longtitude: 106.6358,
    },
    {
        id: 7,
        name: "Station 7",
        operatorId: 3,
        addressInfor: "District 7, Ho Chi Minh City",
        totalPoints: 8,
        chargingPoints: [],
        status: "active",
        latitude: 10.7306,
        longtitude: 106.7218,
    },
    {
        id: 8,
        name: "Station 8",
        operatorId: 3,
        addressInfor: "District 8, Ho Chi Minh City",
        totalPoints: 5,
        chargingPoints: [],
        status: "maintenance",
        latitude: 10.7382,
        longtitude: 106.6702,
    },
    {
        id: 9,
        name: "Station 9",
        operatorId: 3,
        addressInfor: "District 9, Ho Chi Minh City",
        totalPoints: 6,
        chargingPoints: [],
        status: "active",
        latitude: 10.8478,
        longtitude: 106.7852,
    },
    {
        id: 10,
        name: "Station 10",
        operatorId: 2,
        addressInfor: "District 10, Ho Chi Minh City",
        totalPoints: 3,
        chargingPoints: [],
        status: "inactive",
        latitude: 10.7766,
        longtitude: 106.6676,
    },
];