import { ChargingStation } from "@/models/station";

export const sampleStations: ChargingStation[] = [
    {
        id: 1,
        name: "Station 1",
        operatorId: 1,
        addressInfor: "District 1, Ho Chi Minh City",
        totalPoints: 2,
        status: "active",
        coordinate: { latitude: 10.7769, longitude: 106.7009 },
        chargingPoints: [
            {
                id: 101,
                stationId: 1,
                status: "available",
                Connectors: [
                    {
                        id: 1001,
                        pointId: 101,
                        type: "Type 2",
                        maxPowerKW: 22,
                        voltageV: 400,
                    },
                    {
                        id: 1002,
                        pointId: 101,
                        type: "CCS",
                        maxPowerKW: 50,
                        voltageV: 800,
                    },
                ],
            },
            {
                id: 102,
                stationId: 1,
                status: "busy",
                Connectors: [
                    {
                        id: 1003,
                        pointId: 102,
                        type: "Type 1",
                        maxPowerKW: 7.4,
                        voltageV: 230,
                    },
                ],
            },
        ],
        ratings: [
            { user: "Alice", point: 5, comment: "Great station!" },
            { user: "Bob", point: 4, comment: "Convenient coordinate." },
        ],
        usageData: [80, 55, 20, 30, 40, 50, 60, 70, 80, 90, 100, 110, 120, 130, 140, 150, 160, 170, 180, 190, 200, 210, 220, 230],
    },

    {
        id: 2,
        name: "Station 2",
        operatorId: 1,
        addressInfor: "District 2, Ho Chi Minh City",
        totalPoints: 1,
        status: "maintenance",
        coordinate: { latitude: 10.7798, longitude: 106.7153 },
        chargingPoints: [
            {
                id: 201,
                stationId: 2,
                status: "offline",
                Connectors: [
                    {
                        id: 2001,
                        pointId: 201,
                        type: "CHAdeMO",
                        maxPowerKW: 50,
                        voltageV: 500,
                    },
                ],
            },
        ],
        ratings: [
            { user: "Charlie", point: 3, comment: "Average experience." },
        ],
        usageData: [10, 20, 30, 40, 50, 60, 70, 80, 90, 100, 110, 120, 130, 140, 150, 160, 170, 180, 190, 200, 210, 220, 230, 240],
    },

    {
        id: 3,
        name: "Green Boost Hai Bà Trưng",
        operatorId: 3,
        addressInfor: "123 Hai Bà Trưng, Phường 6, Hồ Chí Minh",
        totalPoints: 5,
        status: "Đang hoạt động",
        coordinate: { latitude: 10.7842, longitude: 106.6968 },
        img: ["https://th.bing.com/th/id/R.1c6f8aee48e94773128c686db96a5320?rik=xxLQoQs3YtfAVg&pid=ImgRaw&r=0"],
        chargingPoints: [
            {
                id: 301,
                stationId: 3,
                status: "available",
                Connectors: [
                    {
                        id: 3001,
                        pointId: 301,
                        type: "Type 2",
                        maxPowerKW: 11,
                        voltageV: 400,
                    },
                ],
            },
            {
                id: 302,
                stationId: 3,
                status: "busy",
                Connectors: [
                    {
                        id: 3002,
                        pointId: 302,
                        type: "CCS",
                        maxPowerKW: 100,
                        voltageV: 800,
                    }, {
                        id: 30021,
                        pointId: 302,
                        type: "Type 2",
                        maxPowerKW: 100,
                        voltageV: 800,
                    },
                ],
            },
            {
                id: 303,
                stationId: 3,
                status: "available",
                Connectors: [
                    {
                        id: 3002,
                        pointId: 302,
                        type: "CCS",
                        maxPowerKW: 100,
                        voltageV: 800,
                    },
                ],
            },
            {
                id: 304,
                stationId: 3,
                status: "busy",
                Connectors: [
                    {
                        id: 3002,
                        pointId: 302,
                        type: "CCS",
                        maxPowerKW: 100,
                        voltageV: 800,
                    },
                ],
            },
            {
                id: 305,
                stationId: 3,
                status: "busy",
                Connectors: [
                    {
                        id: 3002,
                        pointId: 302,
                        type: "CCS",
                        maxPowerKW: 100,
                        voltageV: 800,
                    },
                ],
            },
        ],
    },
    {
        id: 4,
        name: "Station 4",
        operatorId: 2,
        addressInfor: "District 4, Ho Chi Minh City",
        totalPoints: 3,
        chargingPoints: [],
        status: "active",
        coordinate: { latitude: 10.7644, longitude: 106.7042 },
    },
    {
        id: 5,
        name: "Station 5",
        operatorId: 2,
        addressInfor: "District 5, Ho Chi Minh City",
        totalPoints: 7,
        chargingPoints: [],
        status: "busy",
        coordinate: { latitude: 10.7596, longitude: 106.6828 },
    },
    {
        id: 6,
        name: "Station 6",
        operatorId: 3,
        addressInfor: "District 6, Ho Chi Minh City",
        totalPoints: 4,
        chargingPoints: [],
        status: "offline",
        coordinate: { latitude: 10.7522, longitude: 106.6358 },
    },
    {
        id: 7,
        name: "Station 7",
        operatorId: 3,
        addressInfor: "District 7, Ho Chi Minh City",
        totalPoints: 8,
        chargingPoints: [],
        status: "active",
        coordinate: { latitude: 10.7306, longitude: 106.7218 },
    },
    {
        id: 8,
        name: "Station 8",
        operatorId: 3,
        addressInfor: "District 8, Ho Chi Minh City",
        totalPoints: 5,
        chargingPoints: [],
        status: "maintenance",
        coordinate: { latitude: 10.7382, longitude: 106.6702 },
    },
    {
        id: 9,
        name: "Station 9",
        operatorId: 3,
        addressInfor: "District 9, Ho Chi Minh City",
        totalPoints: 6,
        chargingPoints: [],
        status: "active",
        coordinate: { latitude: 10.8478, longitude: 106.7852 },
    },
    {
        id: 10,
        name: "Station 10",
        operatorId: 2,
        addressInfor: "District 10, Ho Chi Minh City",
        totalPoints: 3,
        chargingPoints: [],
        status: "inactive",
        coordinate: { latitude: 10.7766, longitude: 106.6676 },
    },
];