spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/charging_service
    username: postgres
    password: 1234
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update  # creates/updates tables automatically
    show-sql: true
    properties:
      hibernate:
        format_sql: true

server:
  port: 8080
