
import type { Metadata } from "next";
import "./globals.css";
import { Saira } from "next/font/google";

import "leaflet/dist/leaflet.css";
import { AuthProvider } from "../context/AuthContext";
import { Header } from "@/components/homePage/Header";
import Head from "next/head";
const sairaFont = Saira({
  subsets: ["vietnamese"],
  weight: "400",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {

  return (
    <html lang="en">
       <Head>
        <link
          rel="stylesheet"
          href="/leaflet-routing-machine.css"
        />
        <script
          src="/leaflet-routing-machine.min.js"
          defer
        />
      </Head>
      <body
        className={`${sairaFont.className}`}
      >
        <AuthProvider>
          <main >{children}</main>
        </AuthProvider>
      </body>
    </html>
  );
}
