spring.application.name=backend
spring.config.import=optional:file:.env.local[.properties]
# change this if you want to use env.local

spring.datasource.url=jdbc:postgresql://${DB_HOST}:${DB_PORT}/${DB_NAME}?reWriteBatchedInserts=true
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.generate_statistics=false
spring.jpa.properties.hibernate.jdbc.batch_size=100
spring.jpa.properties.hibernate.order_inserts=true
spring.jpa.properties.hibernate.order_updates=true

application.security.jwt.secret-key=${API_JWT_KEY}
application.security.jwt.expiration=${JWT_EXPIRATION}

cloud.aws.credentials.access-key=${S3_ACCESS_KEY}
cloud.aws.credentials.secret-key=${S3_SECRET_KEY}
cloud.aws.region.static=${S3_REGION}

aws.bucket.name=${BUCKET_NAME}
